server:
  port: 9000
spring:
  application:
    name: ApiGateWay
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

    eureka:
      client:
        serviceUrl:
          defaultZone: http://eureka-server-service:8761/eureka
        fetch-registry: true
        register-with-eureka: true